---
openapi: 3.0.3
info:
  title: Timetabling for VIT
  description: AI-powered timetabling solution for VIT
  contact:
    name: JetEdge Customer Support
    email: techsupport@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0-SNAPSHOT-oas3
paths:
  /login:
    get:
      summary: Authenticate login
      description: Sends user-entered login details in the HTTP header and authenticates against the credentials stored in the database.
      tags:
        - User Resource
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Not Authorized
        '403':
          description: Not Allowed
      security:
        - defaultApiKey: []
  /rooms:
    get:
      summary: Get all rooms
      description: Retrieves all rooms across all campuses.
      tags:
        - Room Resource
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
        '401':
          description: Not Authorized
        '403':
          description: Not Allowed
      security:
        - defaultApiKey: []
    post:
      summary: Create a room
      description: Sends a room in its correct Java class format.
      tags:
        - Room Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
      responses:
        '200':
          description: OK
        '401':
          description: Not Authorized
        '403':
          description: Not Allowed
      security:
        - defaultApiKey: []
  /timetabling:
    get:
      summary: Get all timetables
      description: Retrives all generated timetables from the database, separated by campus.
      tags:
        - Timetable Resource
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Timetable'
        '401':
          description: Not Authorized
        '403':
          description: Not Allowed
      security:
        - defaultApiKey: []
    post:
      summary: Create a timetabling problem
      description: Sends all information required to construct a timetabling problem.
      tags:
        - Timetable Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Timetable'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Timetable'
        '401':
          description: Not Authorized
        '403':
          description: Not Allowed
      security:
        - defaultApiKey: []
  /timetabling/example:
    get:
      summary: Get hard-coded timetable
      description: Retrieves the solution to a hard-coded timetabling problem.
      tags:
        - Timetable Resource
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Timetable'
        '401':
          description: Not Authorized
        '403':
          description: Not Allowed
  /timetabling/update:
    put:
      summary: Update a timetable
      description: Updates the existing timetable of a campus with a series of drag-and-drop changes committed by the user relating to class time and location.
      tags:
        - Timetable Resource
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Unit'
      responses:
        '200':
          description: OK
  /units:
    get:
      summary: Get all units
      description: Retrieves all units across all campuses.
      tags:
        - Unit Resource
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Unit'
        '401':
          description: Not Authorized
        '403':
          description: Not Allowed
    post:
      summary: Create a unit
      description: Sends a unit in its correct Java class format.
      tags:
        - Unit Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Unit'
      responses:
        '200':
          description: OK
        '401':
          description: Not Authorized
        '403':
          description: Not Allowed
components:
  securitySchemes:
    defaultApiKey:
      description: API key encoded
      type: apiKey
      name: Authorization
      in: header
  schemas:
    DayOfWeek:
      enum:
        - MONDAY
        - TUESDAY
        - WEDNESDAY
        - THURSDAY
        - FRIDAY
        - SATURDAY
        - SUNDAY
      type: string
    Duration:
      format: duration
      type: string
      example: P1D
    HardSoftScore:
      type: object
      properties:
        zero:
          type: boolean
        solutionInitialized:
          type: boolean
        initScore:
          format: int32
          type: integer
        hardScore:
          format: int32
          type: integer
        softScore:
          format: int32
          type: integer
        feasible:
          type: boolean
    LocalTime:
      format: local-time
      type: string
      externalDocs:
        description: As defined by 'partial-time' in RFC3339
        url: https://www.rfc-editor.org/rfc/rfc3339.html#section-5.6
      example: '13:45:30.123456789'
    Room:
      type: object
      properties:
        id:
          format: int64
          type: integer
        roomCode:
          type: string
        buildingId:
          type: string
        campus:
          type: string
        capacity:
          format: int32
          type: integer
        isLab:
          type: boolean
        lab:
          type: boolean
    Student:
      type: object
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
    Timetable:
      type: object
      properties:
        id:
          format: int64
          type: integer
        campusName:
          type: string
        daysOfWeek:
          type: array
          items:
            $ref: '#/components/schemas/DayOfWeek'
        startTimes:
          type: array
          items:
            format: local-time
            type: string
            externalDocs:
              description: As defined by 'partial-time' in RFC3339
              url: https://www.rfc-editor.org/rfc/rfc3339.html#section-5.6
            example: '13:45:30.123456789'
        rooms:
          type: array
          items:
            $ref: '#/components/schemas/Room'
          writeOnly: true
        units:
          type: array
          items:
            $ref: '#/components/schemas/Unit'
        score:
          $ref: '#/components/schemas/HardSoftScore'
    Unit:
      type: object
      properties:
        id:
          format: int64
          type: integer
        unitId:
          format: int32
          type: integer
        name:
          type: string
        course:
          type: string
        duration:
          $ref: '#/components/schemas/Duration'
        dayOfWeek:
          $ref: '#/components/schemas/DayOfWeek'
        startTime:
          $ref: '#/components/schemas/LocalTime'
        students:
          type: array
          items:
            $ref: '#/components/schemas/Student'
        studentSize:
          format: int32
          type: integer
        room:
          $ref: '#/components/schemas/Room'
        wantsLab:
          type: boolean
        end:
          $ref: '#/components/schemas/LocalTime'